### ISSUE TITLE
Crashed after 255 commit 

### ISSUE THREAD

**Issue by jopemachine** [lablup/riteraft-py#8]
<img width="1840" alt="스크린샷 2023-07-17 오후 4 15 22" src="https://github.com/lablup/riteraft-py/assets/18283033/37e8b2a4-6791-463e-a375-1229adfebbd9">

This also happens as in the riteraft.

Ref: https://github.com/ritelabs/riteraft/issues/16

```
Traceback (most recent call last):
  File "/Users/jopemachine/.pyenv/versions/3.11.3/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/Users/jopemachine/.pyenv/versions/3.11.3/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jopemachine/.pyenv/versions/3.11.3/lib/python3.11/site-packages/riteraft/mailbox.py", line 35, in send
    resp = await asyncio.wait_for(receiver.get(), 2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jopemachine/.pyenv/versions/3.11.3/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jopemachine/.pyenv/versions/3.11.3/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jopemachine/.pyenv/versions/3.11.3/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jopemachine/Desktop/riteraft-py/./examples/memstore/main.py", line 80, in put
    result = await mailbox.send(message.encode())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jopemachine/.pyenv/versions/3.11.3/lib/python3.11/site-packages/riteraft/mailbox.py", line 37, in send
    raise UnknownError(str(e))
riteraft.error.UnknownError
```

**Comment by jopemachine** [comment]
<img width="1840" alt="스크린샷 2023-07-19 오후 6 31 09" src="https://github.com/lablup/riteraft-py/assets/18283033/abf38ac3-ef6d-49c1-86bd-a0c5c58c0dbc">

Fixed in d84dec1d5ffc03765947406e3edb72001e1ced2d.

I've noticed that when I pass an integer as a key to `mdb_put`, it only reads the first byte, so I need to replace the integer with str before passing it.
